/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "crossword-generator",
  "name": "Crossword AI",
  "supabaseUrl": "https://izyyaxovwwvjrladiumv.supabase.co",
  "supabaseAnonKey": "sb_publishable_nCqQWacYrOdTDGU9yspukA_jQvQoc9I",
  "aiProxy": "https://ai-proxy.goede-aeb.workers.dev",
  "google": false,
  "prompts": [
    {
      "say": "A crossword about 90s video games, tricky clues",
      "does": "Writes the words and builds the grid."
    },
    {
      "say": "Turn my vocabulary list into a word search",
      "does": "Makes a word search from the Build page words."
    },
    {
      "say": "Give me a hint for 3 down",
      "does": "Reveals one letter of that answer."
    }
  ]
};
